dist: trusty
language: java
jdk:
  - oraclejdk8
  
install:
  - ./gradlew clean jar
script:
  - ./gradlew test
  - COVERAGE="$COVERAGE" ./gradlew test jacocoTestCoverageVerification
after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'
deploy:
  echo "WIP"