dist: trusty
language: java
jdk:
  - $JDK_VERSION
env:
  - JDK_VERSION=oraclejdk8
  - JDK_VERSION=oraclejdk9
install:
  - ./gradlew clean jar
stages:
  - tests
jobs:
  include:
    - stage: tests
      name: "ui"
      install: skip
      script:
        - COVERAGE="$COVERAGE" ./gradlew -p ./monolithic/ui check
    - stage: tests
      name: "service/cart"
      install: skip
      script:
        - COVERAGE="$COVERAGE" ./gradlew -p ./monolithic/service/cart check
    - stage: tests
      name: "service/user"
      install: skip
      script:
        - COVERAGE="$COVERAGE" ./gradlew -p ./monolithic/service/user check
    - stage: tests
      name: "repository/order"
      install: skip
      script:
        - COVERAGE="$COVERAGE" ./gradlew -p ./monolithic/repository/order check
    - stage: tests
      name: "repository/cart"
      install: skip
      script:
        - COVERAGE="$COVERAGE" ./gradlew -p ./monolithic/repository/cart check
    - stage: tests
      name: "repository/product"
      install: skip
      script:
        - COVERAGE="$COVERAGE" ./gradlew -p ./monolithic/repository/product check
    - stage: tests
      name: "repository/user"
      install: skip
      script:
        - COVERAGE="$COVERAGE" ./gradlew -p ./monolithic/repository/user check
deploy:
  echo "WIP"