dist: trusty
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
env:
  - RELPATH=monolithic/ui
  - RELPATH=monolithic/service/cart
  - RELPATH=monolithic/service/user
  - RELPATH=monolithic/repository/order
  - RELPATH=monolithic/repository/cart
  - RELPATH=monolithic/repository/product
  - RELPATH=monolithic/repository/user
install:
  - ./gradlew clean jar
script:
  - COVERAGE="$COVERAGE" ./gradlew -p "./${RELPATH}" check
deploy: echo "WIP"